### ISSUE TITLE
[Bug] Illegal characters in chat. (Tab Complete Nicked Name)

### ISSUE THREAD

**Issue by EnderGamingFilms** [InventivetalentDev/NickNamer#123]
## What steps will reproduce the problem?  
1. /nick &bName
2. Press T and press tab twice
3. Press enter, get kicked from the server.

## What were you expecting to happen? What happened instead?  
Send player nickname in the chat

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.18.2-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Paper 1.14.4

## What plugins are you using? *Type /plugins*  
ChatControl, NickNamer, PacketListenerAPI, PlaceHolderAPI, [Others](https://imgur.com/Kt0Mv57.png)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Nothing

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Yes (First time using this plugin)

**Comment by InventivetalentDev** [comment]
should be fixed :)

**Comment by EnderGamingFilms** [comment]
Still not fixed... Still getting kicked for illegal characters in chat.

![](https://imgur.com/yD8OX0i.jpg)

**Comment by InventivetalentDev** [comment]
Okay, I think this might be quite complicated to fix actually. Due to changes in the client there doesn't seem to be a serverside way of fixing this in the latest versions, since the client uses the player list to create its own completions, where before those were sent by the server.

**Comment by EnderGamingFilms** [comment]
Well couldn't you make the tablist have no colors in it and just require the use of a third party tablist like BungeeTabListPlus so show the colored nick in tab?
